services:
    webserver:
        container_name: webserver
        build:
            context: .
            target: nginx-stage
        ports:
            - "8000:8000"
        volumes:
            - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./:/var/www/html
        depends_on:
            - php
        networks:
            - app-network

    php:
        container_name: php
        build:
            context: .
            target: php-stage
        restart: unless-stopped
        working_dir: /var/www/html
        depends_on:
            mariadb:
                condition: service_healthy
        volumes:
            - ./:/var/www/html
            - ./entrypoint.sh:/root/entrypoint.sh
        networks:
            - app-network

    mariadb:
        container_name: mariadb
        image: mariadb:10.5
        ports:
            - "3306:3306"
        environment:
            - MARIADB_ROOT_PASSWORD=root
            - MARIADB_DATABASE=laravel
            - MARIADB_USER=user
            - MARIADB_PASSWORD=password
        volumes:
            - mariadb-data:/var/lib/mariadb
        networks:
            - app-network
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "mariadb"]
            interval: 10s
            retries: 3
            timeout: 5s

volumes:
    mariadb-data:

networks:
    app-network:
